name: Team Novelli
favicon: null
layout_spectrum: 0.8835
typography_spectrum: 0.1678748414851725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01a6ce'
    - '#c2d845'
    - '#93daec'
    - '#b5b8a5'
  brandStrength: 0.5898998624179512
  lightness: 0.7543436395935714
  saturation: 0.7952126674354076
  rhythmicContrast: 1
purpose: []
